name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  extension:
    runs-on: ubuntu-latest
    env:
      COMPANION_APP_URL: http://localhost
    defaults:
      run:
        working-directory: ./deployables/extension
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.13.1
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - run: pnpm install --prefer-offline
      - run: pnpm test
      - name: 'Report Coverage'
        # Set if: always() to also generate the report if tests are failing
        # Only works if you set `reportOnFailure: true` in your vite config as specified above
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: deployables/extension

  ui-package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/ui
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.13.1
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - run: pnpm install --prefer-offline
      - run: pnpm test

  test-utils:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/test-utils
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.13.1
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - run: pnpm install --prefer-offline
      - run: pnpm test

  pilot-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deployables/app
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.13.1
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - run: pnpm install --prefer-offline
      - run: pnpm test

  modules-package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/modules
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.13.1
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - run: pnpm install --prefer-offline
      - run: pnpm test
